steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_IMAGE', '-f', 'Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_IMAGE']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'radheresume'
  - '--image'
  - '$_IMAGE'
  - '--region'
  - 'us-central1'